#!/bin/sh
# semear.sh — o que a assistente sabe do sistema. Só factos verificáveis no código;
# nada aqui é inventado, e cada par corresponde a algo que a bateria mede.
#   ./semear.sh <base>
# corre de onde for chamado: os caminhos relativos daqui contam a partir de tools/
cd "$(dirname "$0")" || exit 1
B="${1:-/tmp/barr/tiffany}"
# a base tem de existir antes de se escrever nela: cria-se a pasta, e a ferramenta
# deixa de depender de alguem a ter montado antes.
mkdir -p "$(dirname "$B")" 2>/dev/null
# o conversa.c mudou-se para banco/ em 03/08 (é armazenamento, não medição).
# Compila-se de lá; o binário fica em banco/bin/.
A="../banco/bin/conversa"
[ -x "$A" ] || { mkdir -p ../banco/bin && cc -O2 -std=c99 -I../lib ../banco/conversa.c -lm -o "$A"; }
p(){ "$A" "$B" aprende "$1" "$2" >/dev/null; }

# --- os comandos do banco (os que o executa() despacha) ---
p "que comandos o banco tem" "CREATE TABLE, INSERT INTO, SELECT, UPDATE, DELETE, INSERT TEXTO, BUSCA TEXTO, ACHA TEXTO, DISTANCIA, CORPOS, CABECALHO, MARTELO, VERIFICA, MINERA e CONFIG."
p "como crio uma tabela" "sql <base> \"CREATE TABLE t (a,b,c)\" — sem tipo é INTEIRO; há RACIONAL, AUREO, MORFICO e CRISTALINO."
p "como insiro uma linha" "sql <base> \"INSERT INTO t VALUES (1,2,3)\""
p "como leio uma tabela" "sql <base> \"SELECT * FROM t\" — e o WHERE filtra."
p "como corro um script" "sql <base> - lê um comando por linha da entrada; linha vazia e -- são comentário."
p "como guardo uma configuração" "sql <base> \"CONFIG pool_user 'a chave'\" põe, e sql <base> \"CONFIG pool_user\" lê. Fica num ficheiro .conf a 0600."

# --- a cifra e a régua ---
p "o que é a cifra" "É a fração contínua, e é o único sistema de coordenadas do sistema: a mesma para um texto, um número, um corpo, um formato e uma linguagem."
p "como se compara duas coisas" "Anda-se o caminho comum das cifras e para-se no primeiro termo que diverge. A distância é 1/2^k com k o prefixo comum."
p "o que é a régua do rei" "É a do corpo áureo, [1;1,1,1,...] — sigma = 1 + 1/sigma. A indução tem essa cifra: base mais passo, e o passo é sempre o mesmo."
p "quantos corpos há no catálogo" "42 entradas em 18 lugares distintos. Formatos e linguagens entraram e nenhum abriu lugar novo."
p "que corpo é o json" "O áureo — razão 1, sinal -1. O parêntese abre e fecha, e as duas direções cancelam-se. C, Lisp, HTML e o ambiente do TeX caem no mesmo lugar."
p "o que é o decreto" "É o único método sem dual: o absorvente. É ele que diz não sei em vez de inventar."

# --- as réguas do mórfico ---
p "quais são as três réguas" "Erosão (o prefixo), dilatação (a subsequência) e torção (o entrelaçar). São as operações do corpo mórfico, e todas reversíveis."
p "o que é a erosão" "É o prefixo: a fala tal como veio, e o prefixo mais longo que existir. É o WHERE."
p "o que é a dilatação" "É a subsequência: acha a fala com ruído à frente ou no meio, e é o dual da erosão."
p "o que é a torção" "É o entrelaçar: duas falas no mesmo canal, desentrelaçadas. Reverte com o dual, que são os comprimentos."

# --- a mineração ---
p "como ligo a mineração" "CONFIG pool_host, CONFIG pool_user, CONFIG mina_ativa '1', e depois sql <base> MINERA."
p "como paro a mineração" "sql <base> \"CONFIG mina_ativa '0'\" — o worker vê a flag a cada volta e para sozinho. Não é preciso matar processo."
p "o que é o martelo" "MARTELO <de> <ate> varre a faixa de nonces; VERIFICA <nonce> confere. Um estica e o outro contrai — é por isso que o trabalho é prova."
p "o que é o midstate" "Os primeiros 64 bytes do cabeçalho não mudam com o nonce, então a dobra faz-se uma vez por job e não uma vez por nonce. Passou de 1,15 a 1,94 MH/s."
p "o que é a merkle" "É a dobra: pares que se juntam num, nível a nível, até sobrar um. A branch é o desdobramento — o caminho de uma folha até à raiz."

# --- as regras duras ---
p "posso usar ram" "Não. Zero malloc, calloc e realloc no toolkit. O que entra vai para o banco e é de lá que se lê."
p "onde ficam os dados" "No banco, em disco, por pread e pwrite. Nada em memória — nem tabela, nem índice, nem buffer que cresça."
p "o que é o barramento" "É a aplicação. Os bancos reagem ao que nele passa; ninguém é chamado pelo nome e não há registo de quem tem o quê."
p "como sei se algo está certo" "Corre-se a bateria: cada medidor devolve resíduo 0 ou falha. Não há aproximação e não há quase."

# --- operar o sistema (ferramentas reais em tools/) ---
p "como opero o sistema" "Três camadas: (1) conversa na base; (2) TeX vivo via indexa_tex_vivo; (3) bateria para atestar. Exporta TIFFANY_ROOT=\$PWD. Base típica: banco/.fala/vivo."
p "como se opera o sistema" "casual.sh (trato) + semear.sh (operação) + indexa_tex_vivo.sh (ponteiros @TEX) + conversa responde. Bateria: bash tools/bateria.sh."
p "o que é a bateria" "tools/bateria.sh: corre os medidores; VERDE=exit 0, FALHA=resto. Atestados em tools/atestados.txt — não se apagam. Selo = transformada da membrana."
p "como corro a bateria" "bash tools/bateria.sh — lê as DUAS linhas: total e unidades. Para reatestar UM: bash tools/bateria.sh --reatesta <nome>."
p "o que é um atestado" "Linha em tools/atestados.txt: medidor + assinatura do conteúdo + falhas. Atestada a semente, não se re-deriva sem --reatesta."
p "o que é o painel" "tools/painel.sh — estado do piloto agora (hooks, plugues, bateria). Paralelo ao docs/PILOTO.md: o manual diz o que é; o painel diz o estado."
p "como abro o painel" "bash tools/painel.sh — ou painel.sh <verbo> (corpo, plugues, estado, tudo)."
p "como recupero a assistente" "bash tools/recupera_assistente.sh [base] — casual + fundação + índice @TEX vivo. Default: banco/.fala/reino."
p "como indexo o tex vivo" "bash tools/indexa_tex_vivo.sh [base] — só títulos → @TEX caminho. O corpo NÃO se copia; responde() lê o .tex na hora."
p "o que é tex vivo" "A base guarda '@TEX papers/…'; conversa expande lendo o ficheiro AGORA. Alterar o .tex altera a resposta sem reingerir."
p "o que é TIFFANY_ROOT" "Variável de ambiente: raiz do repo. O responde precisa dela (ou achar papers/arquitetura.tex a subir pastas) para abrir os @TEX."
p "como falo com a assistente" "export TIFFANY_ROOT=\$PWD; banco/bin/conversa <base> responde \"…\". Aprende: conversa <base> aprende \"fala\" \"resposta\"."
p "como aprendo um par" "banco/bin/conversa <base> aprende \"a fala\" \"a resposta\" — substitui a resposta no nó. Esquece: resolve_esquece / «esquece X»."
p "qual base uso" "banco/.fala/vivo — tex vivo + operação. banco/.fala/reino — recupera clássica. Sempre com TIFFANY_ROOT=\$PWD para @TEX."
p "como monto a base viva" "export TIFFANY_ROOT=\$PWD; bash tools/casual.sh banco/.fala/vivo; bash tools/semear.sh banco/.fala/vivo; bash tools/indexa_tex_vivo.sh banco/.fala/vivo."
p "como indexo orbitas" "bash tools/indexa_orbitas.sh — gera lib/classe/corpus_orbitas_pt.txt e IMPORT IDIOMA 'pt' no sql (idioma/pt/orbita/…)."
p "o que é IMPORT IDIOMA" "No sql: IMPORT IDIOMA 'pt'|'en'|'es' — indexa alfabeto/lexico/regra; com corpus_orbitas_pt.txt também orbita."
p "onde esta o cursor" "cursor.txt na raiz — ESTADO e §15 A FRENTE AGORA. Não é histórico: é por onde se pega o trabalho."
p "o que e o cursor txt" "cursor.txt: onde está o trabalho e como se segue. Verificar SEMPRE com bash tools/bateria.sh."
p "mostra o piloto" "docs/PILOTO.md — manual do piloto; o estado agora é tools/painel.sh."
p "como compilo a conversa" "cc -O2 -std=c99 -w -Ilib -o banco/bin/conversa banco/conversa.c -lm"
p "como compilo o sql" "cc -O2 -std=c99 -w -Ilib -Ibanco -o /tmp/sqlb banco/sql.c -lm — depois /tmp/sqlb <base> \"…\""

# --- ensinar ciência (corpo nos .tex; aqui só a porta) ---
p "ensina a cadeia" "@TEX corpus/docs/ciencia_dragao.tex"
p "mostra a ciencia do dragao" "@TEX corpus/docs/ciencia_dragao.tex"
p "a cadeia do basico ao dragao" "@TEX corpus/docs/ciencia_dragao.tex"
p "como se ensina" "@TEX corpus/docs/ciencia_dragao.tex"
p "os ticks" "@TEX corpus/docs/ciencia_dragao.tex"
p "membrana latex ascii" "@TEX corpus/docs/ciencia_dragao.tex"
p "resolve 1 mais 1" "@TEX corpus/docs/ciencia_dragao.tex"
p "1 mais 1 em dois corpos" "@TEX corpus/docs/ciencia_dragao.tex"
p "tick dragao" "@TEX corpus/docs/ciencia_dragao.tex"
p "tick bit" "@TEX corpus/docs/ciencia_dragao.tex"
p "o que e o tick" "@TEX corpus/docs/ciencia_dragao.tex"
p "o que é o tick" "@TEX corpus/docs/ciencia_dragao.tex"
p "regua do idioma" "@TEX corpus/docs/ciencia_dragao.tex"
p "régua do idioma" "@TEX corpus/docs/ciencia_dragao.tex"
p "algoritmo inverso e o tick" "@TEX corpus/docs/ciencia_dragao.tex"
p "integrar o tick no algoritmo" "@TEX corpus/docs/ciencia_dragao.tex"
p "o tick na teoria do dragao" "@TEX corpus/docs/ciencia_dragao.tex"

# conservação métrica CM1–CM8 (prosa canónica; testemunhas em cmetrica_resolve)
p "conservacao metrica" "@TEX corpus/docs/conservacao_metrica.tex"
p "conservação métrica" "@TEX corpus/docs/conservacao_metrica.tex"
p "a descida" "@TEX corpus/docs/conservacao_metrica.tex"
p "descida" "@TEX corpus/docs/conservacao_metrica.tex"
p "meta inducao" "@TEX corpus/docs/conservacao_metrica.tex"
p "meta-indução" "@TEX corpus/docs/conservacao_metrica.tex"
p "sem teto" "@TEX corpus/docs/conservacao_metrica.tex"
p "sem tecto" "@TEX corpus/docs/conservacao_metrica.tex"
p "o determinante" "@TEX corpus/docs/conservacao_metrica.tex"
p "determinante factor de volume" "@TEX corpus/docs/conservacao_metrica.tex"
p "quatro contas" "@TEX corpus/docs/conservacao_metrica.tex"
p "o gato e a medida" "@TEX corpus/docs/conservacao_metrica.tex"
p "jacobiano" "@TEX corpus/docs/conservacao_metrica.tex"
p "gume da area" "@TEX corpus/docs/conservacao_metrica.tex"
p "gume da área" "@TEX corpus/docs/conservacao_metrica.tex"
p "representacao" "@TEX corpus/docs/conservacao_metrica.tex"
p "falha de representacao" "@TEX corpus/docs/conservacao_metrica.tex"
p "o passarinho" "@TEX corpus/docs/conservacao_metrica.tex"
p "passarinho" "@TEX corpus/docs/conservacao_metrica.tex"
p "bidualidade" "@TEX corpus/docs/conservacao_metrica.tex"
p "a pata" "@TEX corpus/docs/conservacao_metrica.tex"
p "a marca nao e o estado" "@TEX corpus/docs/conservacao_metrica.tex"
p "dois duais de 32" "@TEX corpus/docs/conservacao_metrica.tex"
p "livro razao" "@TEX corpus/docs/conservacao_metrica.tex"
p "livro-razão" "@TEX corpus/docs/conservacao_metrica.tex"
p "o livro razao" "@TEX corpus/docs/conservacao_metrica.tex"
p "o que cada etapa conserva" "@TEX corpus/docs/conservacao_metrica.tex"
p "dois ramos" "@TEX corpus/docs/conservacao_metrica.tex"
p "gato e esquilo" "@TEX corpus/docs/conservacao_metrica.tex"
p "lei 8" "@TEX corpus/docs/conservacao_metrica.tex"
p "a lei 8" "@TEX corpus/docs/conservacao_metrica.tex"
p "as cinco" "@TEX corpus/docs/conservacao_metrica.tex"
p "as cinco primitivas" "@TEX corpus/docs/conservacao_metrica.tex"
p "zero e infinito" "@TEX corpus/docs/conservacao_metrica.tex"
p "zero e infinito sao inversos" "@TEX corpus/docs/conservacao_metrica.tex"
p "sem ramo" "@TEX corpus/docs/conservacao_metrica.tex"
p "os if vem da normalizacao" "@TEX corpus/docs/conservacao_metrica.tex"
p "a face pequena refuta" "@TEX corpus/docs/conservacao_metrica.tex"
p "refuta" "@TEX corpus/docs/conservacao_metrica.tex"
p "duas testemunhas" "@TEX corpus/docs/conservacao_metrica.tex"
p "um bit" "@TEX corpus/docs/conservacao_metrica.tex"
p "em F2 o dual" "@TEX corpus/docs/conservacao_metrica.tex"
p "um bit em F2" "@TEX corpus/docs/conservacao_metrica.tex"
p "as oito no byte" "@TEX corpus/docs/conservacao_metrica.tex"
p "ascii e cifra" "@TEX corpus/docs/conservacao_metrica.tex"
p "ascii e a cifra" "@TEX corpus/docs/conservacao_metrica.tex"
p "os 128 codigos" "@TEX corpus/docs/conservacao_metrica.tex"
p "os 128 pontos do ascii" "@TEX corpus/docs/conservacao_metrica.tex"

# corpos CP1–CP8 (prosa; testemunhas em corpo_resolve)
p "corpos exercicios" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q e um corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z nao e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z nao corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "unicidade do inverso" "@TEX corpus/docs/corpo_exercicios.tex"
p "o inverso e unico" "@TEX corpus/docs/corpo_exercicios.tex"
p "cancelamento multiplicativo" "@TEX corpus/docs/corpo_exercicios.tex"
p "sem divisores de zero" "@TEX corpus/docs/corpo_exercicios.tex"
p "a caracteristica" "@TEX corpus/docs/corpo_exercicios.tex"
p "caracteristica" "@TEX corpus/docs/corpo_exercicios.tex"
p "Zp e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z6 nao e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z6 nao corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "inversos em F7" "@TEX corpus/docs/corpo_exercicios.tex"
p "carac zero ou primo" "@TEX corpus/docs/corpo_exercicios.tex"
p "a caracteristica e 0 ou prima" "@TEX corpus/docs/corpo_exercicios.tex"
p "p elevado a n" "@TEX corpus/docs/corpo_exercicios.tex"
p "todo corpo finito tem pn" "@TEX corpus/docs/corpo_exercicios.tex"
p "x2-2 irredutivel" "@TEX corpus/docs/corpo_exercicios.tex"
p "x2 menos 2 irredutivel" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q raiz de 2" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q de raiz de 2" "@TEX corpus/docs/corpo_exercicios.tex"
p "constroi F4" "@TEX corpus/docs/corpo_exercicios.tex"
p "F4 como quociente" "@TEX corpus/docs/corpo_exercicios.tex"
p "inversos em F4" "@TEX corpus/docs/corpo_exercicios.tex"
p "quociente e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Kx sobre p irredutivel" "@TEX corpus/docs/corpo_exercicios.tex"
p "polinomio minimo" "@TEX corpus/docs/corpo_exercicios.tex"
p "polinomio minimo de raiz de 3" "@TEX corpus/docs/corpo_exercicios.tex"
p "sem corpo de 6" "@TEX corpus/docs/corpo_exercicios.tex"
p "nao existe corpo com 6" "@TEX corpus/docs/corpo_exercicios.tex"
p "sem corpo de 10" "@TEX corpus/docs/corpo_exercicios.tex"
p "corpo de 9" "@TEX corpus/docs/corpo_exercicios.tex"
p "construcao de F9" "@TEX corpus/docs/corpo_exercicios.tex"
p "multiplicativo ciclico" "@TEX corpus/docs/corpo_exercicios.tex"
p "K vezes e ciclico" "@TEX corpus/docs/corpo_exercicios.tex"
p "primitivo de F7" "@TEX corpus/docs/corpo_exercicios.tex"
p "fermat pelo grupo" "@TEX corpus/docs/corpo_exercicios.tex"
p "pequeno fermat pelo grupo" "@TEX corpus/docs/corpo_exercicios.tex"
p "inverso por euclides" "@TEX corpus/docs/corpo_exercicios.tex"
p "a orbita e o corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "euclides mdc bezout inverso corpo" "@TEX corpus/docs/corpo_exercicios.tex"

# álgebra moderna AL1–AL8
p "algebra moderna" "@TEX corpus/docs/algebra_moderna.tex"
p "o neutro e unico" "@TEX corpus/docs/algebra_moderna.tex"
p "identidade unica" "@TEX corpus/docs/algebra_moderna.tex"
p "inverso unico no grupo" "@TEX corpus/docs/algebra_moderna.tex"
p "cancelamento em grupo" "@TEX corpus/docs/algebra_moderna.tex"
p "todo subgrupo contem o neutro" "@TEX corpus/docs/algebra_moderna.tex"
p "intersecao de subgrupos" "@TEX corpus/docs/algebra_moderna.tex"
p "imagem de homomorfismo" "@TEX corpus/docs/algebra_moderna.tex"
p "nucleo e normal" "@TEX corpus/docs/algebra_moderna.tex"
p "injetivo sse nucleo trivial" "@TEX corpus/docs/algebra_moderna.tex"
p "lagrange classes laterais" "@TEX corpus/docs/algebra_moderna.tex"
p "teorema de lagrange" "@TEX corpus/docs/algebra_moderna.tex"
p "cayley permutacoes" "@TEX corpus/docs/algebra_moderna.tex"
p "todo grupo e permutacoes" "@TEX corpus/docs/algebra_moderna.tex"
p "primeiro isomorfismo" "@TEX corpus/docs/algebra_moderna.tex"
p "G ker f cong Im f" "@TEX corpus/docs/algebra_moderna.tex"
p "ideais sao nucleos" "@TEX corpus/docs/algebra_moderna.tex"
p "iso de aneis" "@TEX corpus/docs/algebra_moderna.tex"
p "ideais de Z" "@TEX corpus/docs/algebra_moderna.tex"
p "todo ideal de Z e nZ" "@TEX corpus/docs/algebra_moderna.tex"
p "corpo e dominio" "@TEX corpus/docs/algebra_moderna.tex"
p "operacao a mais b mais 1" "@TEX corpus/docs/algebra_moderna.tex"
p "nao associativa" "@TEX corpus/docs/algebra_moderna.tex"
p "a menos b nao e associativa" "@TEX corpus/docs/algebra_moderna.tex"
p "todo grupo comuta" "@TEX corpus/docs/algebra_moderna.tex"
p "todo grupo e comutativo" "@TEX corpus/docs/algebra_moderna.tex"
p "recusa abeliano" "@TEX corpus/docs/algebra_moderna.tex"
p "exponencial soma produto" "@TEX corpus/docs/algebra_moderna.tex"
p "soma vira produto" "@TEX corpus/docs/algebra_moderna.tex"
p "menos vezes" "@TEX corpus/docs/algebra_moderna.tex"
p "oposto atravessa o produto" "@TEX corpus/docs/algebra_moderna.tex"

# cálculo I CL1–CL8
p "calculo I" "@TEX corpus/docs/calculo_exercicios.tex"
p "unicidade do limite" "@TEX corpus/docs/calculo_exercicios.tex"
p "o limite e unico" "@TEX corpus/docs/calculo_exercicios.tex"
p "limite da soma" "@TEX corpus/docs/calculo_exercicios.tex"
p "sanduiche" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema do sanduiche" "@TEX corpus/docs/calculo_exercicios.tex"
p "polinomio continuo" "@TEX corpus/docs/calculo_exercicios.tex"
p "valor intermediario" "@TEX corpus/docs/calculo_exercicios.tex"
p "bissecao e o corte" "@TEX corpus/docs/calculo_exercicios.tex"
p "derivada por quociente" "@TEX corpus/docs/calculo_exercicios.tex"
p "derivada e avaliacao" "@TEX corpus/docs/calculo_exercicios.tex"
p "regra do produto" "@TEX corpus/docs/calculo_exercicios.tex"
p "regra da cadeia" "@TEX corpus/docs/calculo_exercicios.tex"
p "fermat extremo interior" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema de fermat extremos" "@TEX corpus/docs/calculo_exercicios.tex"
p "rolle" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema de rolle" "@TEX corpus/docs/calculo_exercicios.tex"
p "valor medio" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema do valor medio" "@TEX corpus/docs/calculo_exercicios.tex"
p "monotonia" "@TEX corpus/docs/calculo_exercicios.tex"
p "extremos de x3 menos 3x" "@TEX corpus/docs/calculo_exercicios.tex"
p "soma de riemann" "@TEX corpus/docs/calculo_exercicios.tex"
p "telescopagem exacta" "@TEX corpus/docs/calculo_exercicios.tex"
p "propriedades da integral" "@TEX corpus/docs/calculo_exercicios.tex"
p "fundamental i" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema fundamental primeira forma" "@TEX corpus/docs/calculo_exercicios.tex#fundamental i"
p "teorema fundamental segunda forma" "@TEX corpus/docs/calculo_exercicios.tex#fundamental ii"
p "a volta do tfc" "@TEX corpus/docs/calculo_exercicios.tex#fundamental ii"
p "substituicao e a cadeia invertida" "@TEX corpus/docs/calculo_exercicios.tex#substituicao"
p "integracao por partes" "@TEX corpus/docs/calculo_exercicios.tex#integracao por partes"
p "partes e o produto invertido" "@TEX corpus/docs/calculo_exercicios.tex#integracao por partes"
p "analise completa de x3 menos 3x" "@TEX corpus/docs/calculo_exercicios.tex#analise completa"
p "traducao no corpo universal" "@TEX corpus/docs/calculo_exercicios.tex#traducao"
p "cada teorema no universal" "@TEX corpus/docs/calculo_exercicios.tex#traducao"
# análise real AR1–AR8
p "analise real" "@TEX corpus/docs/analise_exercicios.tex"
p "existencia do supremo" "@TEX corpus/docs/analise_exercicios.tex#supremo"
p "sup e inf separados" "@TEX corpus/docs/analise_exercicios.tex#supremo"
p "propriedade arquimediana" "@TEX corpus/docs/analise_exercicios.tex#arquimediana"
p "n construtivo para epsilon" "@TEX corpus/docs/analise_exercicios.tex#arquimediana"
p "ponto medio entre racionais" "@TEX corpus/docs/analise_exercicios.tex#densidade"
p "densidade de Q" "@TEX corpus/docs/analise_exercicios.tex#densidade"
p "irracionais densos sem avaliar" "@TEX corpus/docs/analise_exercicios.tex#irracionais densos"
p "corte de dedekind de raiz de 2" "@TEX corpus/docs/analise_exercicios.tex#dedekind"
p "cauchy sem usar o limite" "@TEX corpus/docs/analise_exercicios.tex#cauchy em Q"
p "completude duas direccoes" "@TEX corpus/docs/analise_exercicios.tex#completude"
p "cauchy equivale a supremo" "@TEX corpus/docs/analise_exercicios.tex#completude"
p "bolzano weierstrass procurada" "@TEX corpus/docs/analise_exercicios.tex#bolzano"
p "subsucessao por bissecao" "@TEX corpus/docs/analise_exercicios.tex#bolzano"
# análise real AR9–AR16
p "n construido de epsilon" "@TEX corpus/docs/analise_exercicios.tex#epsilon N"
p "limite com N explicito" "@TEX corpus/docs/analise_exercicios.tex#epsilon N"
p "dois limites provam divergencia" "@TEX corpus/docs/analise_exercicios.tex#duas subsucessoes"
p "limsup igual liminf" "@TEX corpus/docs/analise_exercicios.tex#limsup"
p "tres formas da continuidade" "@TEX corpus/docs/analise_exercicios.tex#tres continuidades"
p "continua e nao uniformemente" "@TEX corpus/docs/analise_exercicios.tex#uniforme"
p "um sobre x nao uniforme" "@TEX corpus/docs/analise_exercicios.tex#uniforme"
p "limite dentro do compacto" "@TEX corpus/docs/analise_exercicios.tex#compacto"
p "heine borel duas direccoes" "@TEX corpus/docs/analise_exercicios.tex#heine borel"
p "fechado limitado e compacto" "@TEX corpus/docs/analise_exercicios.tex#heine borel"
p "weierstrass atinge extremos" "@TEX corpus/docs/analise_exercicios.tex#weierstrass"
p "continua em compacto atinge" "@TEX corpus/docs/analise_exercicios.tex#weierstrass"
# análise real AR17–AR25
p "limite contra quociente" "@TEX corpus/docs/analise_exercicios.tex#derivada limite e quociente"
p "derivada limite e quociente" "@TEX corpus/docs/analise_exercicios.tex#derivada limite e quociente"
p "valor medio na analise" "@TEX corpus/docs/analise_exercicios.tex#valor medio na analise"
p "c pode ser irracional" "@TEX corpus/docs/analise_exercicios.tex#valor medio na analise"
p "rolle e o gume" "@TEX corpus/docs/analise_exercicios.tex#rolle e o gume"
p "gume de rolle" "@TEX corpus/docs/analise_exercicios.tex#rolle e o gume"
p "resto de taylor medido" "@TEX corpus/docs/analise_exercicios.tex#taylor"
p "criterios estruturais de series" "@TEX corpus/docs/analise_exercicios.tex#series"
p "xn pontual nao uniforme" "@TEX corpus/docs/analise_exercicios.tex#convergencia uniforme"
p "u menos l exacto" "@TEX corpus/docs/analise_exercicios.tex#riemann"
p "troca lim int sob que hipotese" "@TEX corpus/docs/analise_exercicios.tex#troca de limite"
p "cinco vias da completude" "@TEX corpus/docs/analise_exercicios.tex#cinco vias"
p "nenhuma arbitra as outras" "@TEX corpus/docs/analise_exercicios.tex#cinco vias"
# cálculo II C2-1–C2-8
p "calculo II" "@TEX corpus/docs/calculo2_exercicios.tex"
p "partes sai do produto" "@TEX corpus/docs/calculo2_exercicios.tex#partes"
p "integracao por partes no produto" "@TEX corpus/docs/calculo2_exercicios.tex#partes"
p "integral impropria p maior que 1" "@TEX corpus/docs/calculo2_exercicios.tex#impropria"
p "n sobre n mais 1 com N" "@TEX corpus/docs/calculo2_exercicios.tex#sequencia"
p "limitada monotona converge" "@TEX corpus/docs/calculo2_exercicios.tex#bolzano monotona"
p "serie e objecto formal" "@TEX corpus/docs/calculo2_exercicios.tex#serie"
p "termo geral necessario nao suficiente" "@TEX corpus/docs/calculo2_exercicios.tex#termo geral"
p "serie p por telescopagem" "@TEX corpus/docs/calculo2_exercicios.tex#serie p"
p "geometrica formal sem convergencia" "@TEX corpus/docs/calculo2_exercicios.tex#geometrica"
# cálculo II C2-9–C2-16
p "raio e os extremos a parte" "@TEX corpus/docs/calculo2_exercicios.tex#raio"
p "taylor pelos coeficientes" "@TEX corpus/docs/calculo2_exercicios.tex#taylor momentos"
p "coeficientes sao momentos" "@TEX corpus/docs/calculo2_exercicios.tex#taylor momentos"
p "exp seno cosseno nos coeficientes" "@TEX corpus/docs/calculo2_exercicios.tex#exp seno cosseno"
p "parciais formais e exactas" "@TEX corpus/docs/calculo2_exercicios.tex#parciais"
p "gradiente e o dual" "@TEX corpus/docs/calculo2_exercicios.tex#gradiente"
p "schwarz verificado nos coeficientes" "@TEX corpus/docs/calculo2_exercicios.tex#schwarz"
p "derivada e operador linear" "@TEX corpus/docs/calculo2_exercicios.tex#derivada linear"
p "cadeia multiplica matrizes" "@TEX corpus/docs/calculo2_exercicios.tex#cadeia multi"
# cálculo II C2-17–C2-21
p "hessiana e a assinatura" "@TEX corpus/docs/calculo2_exercicios.tex#hessiana"
p "sela minimo maximo degenerada" "@TEX corpus/docs/calculo2_exercicios.tex#hessiana"
p "lagrange multiplicadores" "@TEX corpus/docs/calculo2_exercicios.tex#lagrange multiplicadores"
p "gume da regularidade do vinculo" "@TEX corpus/docs/calculo2_exercicios.tex#lagrange multiplicadores"
p "fubini duas ordens" "@TEX corpus/docs/calculo2_exercicios.tex#fubini"
p "jacobiano medida de volume" "@TEX corpus/docs/calculo2_exercicios.tex#jacobiano"
p "green interior contra borda" "@TEX corpus/docs/calculo2_exercicios.tex#green"
p "borda determina o interior" "@TEX corpus/docs/calculo2_exercicios.tex#green"
# cálculo III C3-1–C3-8
p "calculo III" "@TEX corpus/docs/calculo3_exercicios.tex"
p "limite por caminhos em Rn" "@TEX corpus/docs/calculo3_exercicios.tex#limite por caminhos"
p "dois caminhos matam o limite" "@TEX corpus/docs/calculo3_exercicios.tex#limite por caminhos"
p "bola aberta substitui intervalo" "@TEX corpus/docs/calculo3_exercicios.tex#bola"
p "direcional e maior crescimento" "@TEX corpus/docs/calculo3_exercicios.tex#direcional"
p "plano tangente exacto no resto" "@TEX corpus/docs/calculo3_exercicios.tex#plano tangente"
p "diferencial e o funcional" "@TEX corpus/docs/calculo3_exercicios.tex#diferencial"
p "jacobiana multiplica operadores" "@TEX corpus/docs/calculo3_exercicios.tex#jacobiana"
p "taylor multi exacto" "@TEX corpus/docs/calculo3_exercicios.tex#taylor multi"
p "ponto critico quatro estados" "@TEX corpus/docs/calculo3_exercicios.tex#ponto critico"
# cálculo III C3-9–C3-16
p "lagrange vinculo regular" "@TEX corpus/docs/calculo3_exercicios.tex#lagrange vinculo"
p "integral multipla e fubini" "@TEX corpus/docs/calculo3_exercicios.tex#integral multipla"
p "jacobiano e a medida" "@TEX corpus/docs/calculo3_exercicios.tex#jacobiano volume"
p "coordenadas e o factor" "@TEX corpus/docs/calculo3_exercicios.tex#coordenadas"
p "div atravessa rot roda" "@TEX corpus/docs/calculo3_exercicios.tex#campo"
p "conservativo e a fibra" "@TEX corpus/docs/calculo3_exercicios.tex#conservativo"
p "trabalho independente do caminho" "@TEX corpus/docs/calculo3_exercicios.tex#trabalho"
p "integral de linha e circulacao" "@TEX corpus/docs/calculo3_exercicios.tex#integral de linha"
# cálculo III C3-17–C3-21
p "fluxo pela superficie" "@TEX corpus/docs/calculo3_exercicios.tex#fluxo"
p "green no plano" "@TEX corpus/docs/calculo3_exercicios.tex#green no plano"
p "stokes rot face" "@TEX corpus/docs/calculo3_exercicios.tex#stokes rot face"
p "gauss fluxo caixa" "@TEX corpus/docs/calculo3_exercicios.tex#gauss fluxo caixa"
p "green stokes gauss mesma estrutura" "@TEX corpus/docs/calculo3_exercicios.tex#a mesma estrutura"
p "falta o d exterior" "@TEX corpus/docs/calculo3_exercicios.tex#a mesma estrutura"
