#!/bin/sh
# semear.sh — o que a assistente sabe do sistema. Só factos verificáveis no código;
# nada aqui é inventado, e cada par corresponde a algo que a bateria mede.
#   ./semear.sh <base>
# corre de onde for chamado: os caminhos relativos daqui contam a partir de tools/
cd "$(dirname "$0")" || exit 1
B="${1:-/tmp/barr/tiffany}"
# a base tem de existir antes de se escrever nela: cria-se a pasta, e a ferramenta
# deixa de depender de alguem a ter montado antes.
mkdir -p "$(dirname "$B")" 2>/dev/null
# o conversa.c mudou-se para banco/ em 03/08 (é armazenamento, não medição).
# Compila-se de lá; o binário fica em banco/bin/.
A="../banco/bin/conversa"
[ -x "$A" ] || { mkdir -p ../banco/bin && cc -O2 -std=c99 -I../lib ../banco/conversa.c -lm -o "$A"; }
p(){ "$A" "$B" aprende "$1" "$2" >/dev/null; }

# --- os comandos do banco (os que o executa() despacha) ---
p "que comandos o banco tem" "CREATE TABLE, INSERT INTO, SELECT, UPDATE, DELETE, INSERT TEXTO, BUSCA TEXTO, ACHA TEXTO, DISTANCIA, CORPOS, CABECALHO, MARTELO, VERIFICA, MINERA e CONFIG."
p "como crio uma tabela" "sql <base> \"CREATE TABLE t (a,b,c)\" — sem tipo é INTEIRO; há RACIONAL, AUREO, MORFICO e CRISTALINO."
p "como insiro uma linha" "sql <base> \"INSERT INTO t VALUES (1,2,3)\""
p "como leio uma tabela" "sql <base> \"SELECT * FROM t\" — e o WHERE filtra."
p "como corro um script" "sql <base> - lê um comando por linha da entrada; linha vazia e -- são comentário."
p "como guardo uma configuração" "sql <base> \"CONFIG pool_user 'a chave'\" põe, e sql <base> \"CONFIG pool_user\" lê. Fica num ficheiro .conf a 0600."

# --- a cifra e a régua ---
p "o que é a cifra" "É a fração contínua, e é o único sistema de coordenadas do sistema: a mesma para um texto, um número, um corpo, um formato e uma linguagem."
p "como se compara duas coisas" "Anda-se o caminho comum das cifras e para-se no primeiro termo que diverge. A distância é 1/2^k com k o prefixo comum."
p "o que é a régua do rei" "É a do corpo áureo, [1;1,1,1,...] — sigma = 1 + 1/sigma. A indução tem essa cifra: base mais passo, e o passo é sempre o mesmo."
p "quantos corpos há no catálogo" "42 entradas em 18 lugares distintos. Formatos e linguagens entraram e nenhum abriu lugar novo."
p "que corpo é o json" "O áureo — razão 1, sinal -1. O parêntese abre e fecha, e as duas direções cancelam-se. C, Lisp, HTML e o ambiente do TeX caem no mesmo lugar."
p "o que é o decreto" "É o único método sem dual: o absorvente. É ele que diz não sei em vez de inventar."

# --- as réguas do mórfico ---
p "quais são as três réguas" "Erosão (o prefixo), dilatação (a subsequência) e torção (o entrelaçar). São as operações do corpo mórfico, e todas reversíveis."
p "o que é a erosão" "É o prefixo: a fala tal como veio, e o prefixo mais longo que existir. É o WHERE."
p "o que é a dilatação" "É a subsequência: acha a fala com ruído à frente ou no meio, e é o dual da erosão."
p "o que é a torção" "É o entrelaçar: duas falas no mesmo canal, desentrelaçadas. Reverte com o dual, que são os comprimentos."

# --- a mineração ---
p "como ligo a mineração" "CONFIG pool_host, CONFIG pool_user, CONFIG mina_ativa '1', e depois sql <base> MINERA."
p "como paro a mineração" "sql <base> \"CONFIG mina_ativa '0'\" — o worker vê a flag a cada volta e para sozinho. Não é preciso matar processo."
p "o que é o martelo" "MARTELO <de> <ate> varre a faixa de nonces; VERIFICA <nonce> confere. Um estica e o outro contrai — é por isso que o trabalho é prova."
p "o que é o midstate" "Os primeiros 64 bytes do cabeçalho não mudam com o nonce, então a dobra faz-se uma vez por job e não uma vez por nonce. Passou de 1,15 a 1,94 MH/s."
p "o que é a merkle" "É a dobra: pares que se juntam num, nível a nível, até sobrar um. A branch é o desdobramento — o caminho de uma folha até à raiz."

# --- as regras duras ---
p "posso usar ram" "Não. Zero malloc, calloc e realloc no toolkit. O que entra vai para o banco e é de lá que se lê."
p "onde ficam os dados" "No banco, em disco, por pread e pwrite. Nada em memória — nem tabela, nem índice, nem buffer que cresça."
p "o que é o barramento" "É a aplicação. Os bancos reagem ao que nele passa; ninguém é chamado pelo nome e não há registo de quem tem o quê."
p "como sei se algo está certo" "Corre-se a bateria: cada medidor devolve resíduo 0 ou falha. Não há aproximação e não há quase."

# --- operar o sistema (ferramentas reais em tools/) ---
p "como opero o sistema" "Três camadas: (1) conversa na base; (2) TeX vivo via indexa_tex_vivo; (3) bateria para atestar. Exporta TIFFANY_ROOT=\$PWD. Base típica: banco/.fala/vivo."
p "como se opera o sistema" "casual.sh (trato) + semear.sh (operação) + indexa_tex_vivo.sh (ponteiros @TEX) + conversa responde. Bateria: bash tools/bateria.sh."
p "o que é a bateria" "tools/bateria.sh: corre os medidores; VERDE=exit 0, FALHA=resto. Atestados em tools/atestados.txt — não se apagam. Selo = transformada da membrana."
p "como corro a bateria" "bash tools/bateria.sh — lê as DUAS linhas: total e unidades. Para reatestar UM: bash tools/bateria.sh --reatesta <nome>."
p "o que é um atestado" "Linha em tools/atestados.txt: medidor + assinatura do conteúdo + falhas. Atestada a semente, não se re-deriva sem --reatesta."
p "o que é o painel" "tools/painel.sh — estado do piloto agora (hooks, plugues, bateria). Paralelo ao docs/PILOTO.md: o manual diz o que é; o painel diz o estado."
p "como abro o painel" "bash tools/painel.sh — ou painel.sh <verbo> (corpo, plugues, estado, tudo)."
p "como recupero a assistente" "bash tools/recupera_assistente.sh [base] — casual + fundação + índice @TEX vivo. Default: banco/.fala/reino."
p "como indexo o tex vivo" "bash tools/indexa_tex_vivo.sh [base] — só títulos → @TEX caminho. O corpo NÃO se copia; responde() lê o .tex na hora."
p "o que é tex vivo" "A base guarda '@TEX papers/…'; conversa expande lendo o ficheiro AGORA. Alterar o .tex altera a resposta sem reingerir."
p "o que é TIFFANY_ROOT" "Variável de ambiente: raiz do repo. O responde precisa dela (ou achar papers/arquitetura.tex a subir pastas) para abrir os @TEX."
p "como falo com a assistente" "export TIFFANY_ROOT=\$PWD; banco/bin/conversa <base> responde \"…\". Aprende: conversa <base> aprende \"fala\" \"resposta\"."
p "como aprendo um par" "banco/bin/conversa <base> aprende \"a fala\" \"a resposta\" — substitui a resposta no nó. Esquece: resolve_esquece / «esquece X»."
p "qual base uso" "banco/.fala/vivo — tex vivo + operação. banco/.fala/reino — recupera clássica. Sempre com TIFFANY_ROOT=\$PWD para @TEX."
p "como monto a base viva" "export TIFFANY_ROOT=\$PWD; bash tools/casual.sh banco/.fala/vivo; bash tools/semear.sh banco/.fala/vivo; bash tools/indexa_tex_vivo.sh banco/.fala/vivo."
p "como indexo orbitas" "bash tools/indexa_orbitas.sh — gera lib/classe/corpus_orbitas_pt.txt e IMPORT IDIOMA 'pt' no sql (idioma/pt/orbita/…)."
p "o que é IMPORT IDIOMA" "No sql: IMPORT IDIOMA 'pt'|'en'|'es' — indexa alfabeto/lexico/regra; com corpus_orbitas_pt.txt também orbita."
p "onde esta o cursor" "cursor.txt na raiz — ESTADO e §15 A FRENTE AGORA. Não é histórico: é por onde se pega o trabalho."
p "o que e o cursor txt" "cursor.txt: onde está o trabalho e como se segue. Verificar SEMPRE com bash tools/bateria.sh."
p "mostra o piloto" "docs/PILOTO.md — manual do piloto; o estado agora é tools/painel.sh."
p "como compilo a conversa" "cc -O2 -std=c99 -w -Ilib -o banco/bin/conversa banco/conversa.c -lm"
p "como compilo o sql" "cc -O2 -std=c99 -w -Ilib -Ibanco -o /tmp/sqlb banco/sql.c -lm — depois /tmp/sqlb <base> \"…\""

# --- ensinar ciência (corpo nos .tex; aqui só a porta) ---
p "ensina a cadeia" "@TEX corpus/docs/ciencia_dragao.tex"
p "mostra a ciencia do dragao" "@TEX corpus/docs/ciencia_dragao.tex"
p "a cadeia do basico ao dragao" "@TEX corpus/docs/ciencia_dragao.tex"
p "como se ensina" "@TEX corpus/docs/ciencia_dragao.tex"
p "os ticks" "@TEX corpus/docs/ciencia_dragao.tex"
p "membrana latex ascii" "@TEX corpus/docs/ciencia_dragao.tex"
p "resolve 1 mais 1" "@TEX corpus/docs/ciencia_dragao.tex"
p "1 mais 1 em dois corpos" "@TEX corpus/docs/ciencia_dragao.tex"
p "tick dragao" "@TEX corpus/docs/ciencia_dragao.tex"
p "tick bit" "@TEX corpus/docs/ciencia_dragao.tex"
p "o que e o tick" "@TEX corpus/docs/ciencia_dragao.tex"
p "o que é o tick" "@TEX corpus/docs/ciencia_dragao.tex"
p "regua do idioma" "@TEX corpus/docs/ciencia_dragao.tex"
p "régua do idioma" "@TEX corpus/docs/ciencia_dragao.tex"
p "algoritmo inverso e o tick" "@TEX corpus/docs/ciencia_dragao.tex"
p "integrar o tick no algoritmo" "@TEX corpus/docs/ciencia_dragao.tex"
p "o tick na teoria do dragao" "@TEX corpus/docs/ciencia_dragao.tex"

# conservação métrica CM1–CM8 (prosa canónica; testemunhas em cmetrica_resolve)
p "conservacao metrica" "@TEX corpus/docs/conservacao_metrica.tex"
p "conservação métrica" "@TEX corpus/docs/conservacao_metrica.tex"
p "a descida" "@TEX corpus/docs/conservacao_metrica.tex"
p "descida" "@TEX corpus/docs/conservacao_metrica.tex"
p "meta inducao" "@TEX corpus/docs/conservacao_metrica.tex"
p "meta-indução" "@TEX corpus/docs/conservacao_metrica.tex"
p "sem teto" "@TEX corpus/docs/conservacao_metrica.tex"
p "sem tecto" "@TEX corpus/docs/conservacao_metrica.tex"
p "o determinante" "@TEX corpus/docs/conservacao_metrica.tex"
p "determinante factor de volume" "@TEX corpus/docs/conservacao_metrica.tex"
p "quatro contas" "@TEX corpus/docs/conservacao_metrica.tex"
p "o gato e a medida" "@TEX corpus/docs/conservacao_metrica.tex"
p "jacobiano" "@TEX corpus/docs/conservacao_metrica.tex"
p "gume da area" "@TEX corpus/docs/conservacao_metrica.tex"
p "gume da área" "@TEX corpus/docs/conservacao_metrica.tex"
p "representacao" "@TEX corpus/docs/conservacao_metrica.tex"
p "falha de representacao" "@TEX corpus/docs/conservacao_metrica.tex"
p "o passarinho" "@TEX corpus/docs/conservacao_metrica.tex"
p "passarinho" "@TEX corpus/docs/conservacao_metrica.tex"
p "bidualidade" "@TEX corpus/docs/conservacao_metrica.tex"
p "a pata" "@TEX corpus/docs/conservacao_metrica.tex"
p "a marca nao e o estado" "@TEX corpus/docs/conservacao_metrica.tex"
p "dois duais de 32" "@TEX corpus/docs/conservacao_metrica.tex"
p "livro razao" "@TEX corpus/docs/conservacao_metrica.tex"
p "livro-razão" "@TEX corpus/docs/conservacao_metrica.tex"
p "o livro razao" "@TEX corpus/docs/conservacao_metrica.tex"
p "o que cada etapa conserva" "@TEX corpus/docs/conservacao_metrica.tex"
p "dois ramos" "@TEX corpus/docs/conservacao_metrica.tex"
p "gato e esquilo" "@TEX corpus/docs/conservacao_metrica.tex"
p "lei 8" "@TEX corpus/docs/conservacao_metrica.tex"
p "a lei 8" "@TEX corpus/docs/conservacao_metrica.tex"
p "as cinco" "@TEX corpus/docs/conservacao_metrica.tex"
p "as cinco primitivas" "@TEX corpus/docs/conservacao_metrica.tex"
p "zero e infinito" "@TEX corpus/docs/conservacao_metrica.tex"
p "zero e infinito sao inversos" "@TEX corpus/docs/conservacao_metrica.tex"
p "sem ramo" "@TEX corpus/docs/conservacao_metrica.tex"
p "os if vem da normalizacao" "@TEX corpus/docs/conservacao_metrica.tex"
p "a face pequena refuta" "@TEX corpus/docs/conservacao_metrica.tex"
p "refuta" "@TEX corpus/docs/conservacao_metrica.tex"
p "duas testemunhas" "@TEX corpus/docs/conservacao_metrica.tex"
p "um bit" "@TEX corpus/docs/conservacao_metrica.tex"
p "em F2 o dual" "@TEX corpus/docs/conservacao_metrica.tex"
p "um bit em F2" "@TEX corpus/docs/conservacao_metrica.tex"
p "as oito no byte" "@TEX corpus/docs/conservacao_metrica.tex"
p "ascii e cifra" "@TEX corpus/docs/conservacao_metrica.tex"
p "ascii e a cifra" "@TEX corpus/docs/conservacao_metrica.tex"
p "os 128 codigos" "@TEX corpus/docs/conservacao_metrica.tex"
p "os 128 pontos do ascii" "@TEX corpus/docs/conservacao_metrica.tex"

# corpos CP1–CP8 (prosa; testemunhas em corpo_resolve)
p "corpos exercicios" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q e um corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z nao e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z nao corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "unicidade do inverso" "@TEX corpus/docs/corpo_exercicios.tex"
p "o inverso e unico" "@TEX corpus/docs/corpo_exercicios.tex"
p "cancelamento multiplicativo" "@TEX corpus/docs/corpo_exercicios.tex"
p "sem divisores de zero" "@TEX corpus/docs/corpo_exercicios.tex"
p "a caracteristica" "@TEX corpus/docs/corpo_exercicios.tex"
p "caracteristica" "@TEX corpus/docs/corpo_exercicios.tex"
p "Zp e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z6 nao e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Z6 nao corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "inversos em F7" "@TEX corpus/docs/corpo_exercicios.tex"
p "carac zero ou primo" "@TEX corpus/docs/corpo_exercicios.tex"
p "a caracteristica e 0 ou prima" "@TEX corpus/docs/corpo_exercicios.tex"
p "p elevado a n" "@TEX corpus/docs/corpo_exercicios.tex"
p "todo corpo finito tem pn" "@TEX corpus/docs/corpo_exercicios.tex"
p "x2-2 irredutivel" "@TEX corpus/docs/corpo_exercicios.tex"
p "x2 menos 2 irredutivel" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q raiz de 2" "@TEX corpus/docs/corpo_exercicios.tex"
p "Q de raiz de 2" "@TEX corpus/docs/corpo_exercicios.tex"
p "constroi F4" "@TEX corpus/docs/corpo_exercicios.tex"
p "F4 como quociente" "@TEX corpus/docs/corpo_exercicios.tex"
p "inversos em F4" "@TEX corpus/docs/corpo_exercicios.tex"
p "quociente e corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "Kx sobre p irredutivel" "@TEX corpus/docs/corpo_exercicios.tex"
p "polinomio minimo" "@TEX corpus/docs/corpo_exercicios.tex"
p "polinomio minimo de raiz de 3" "@TEX corpus/docs/corpo_exercicios.tex"
p "sem corpo de 6" "@TEX corpus/docs/corpo_exercicios.tex"
p "nao existe corpo com 6" "@TEX corpus/docs/corpo_exercicios.tex"
p "sem corpo de 10" "@TEX corpus/docs/corpo_exercicios.tex"
p "corpo de 9" "@TEX corpus/docs/corpo_exercicios.tex"
p "construcao de F9" "@TEX corpus/docs/corpo_exercicios.tex"
p "multiplicativo ciclico" "@TEX corpus/docs/corpo_exercicios.tex"
p "K vezes e ciclico" "@TEX corpus/docs/corpo_exercicios.tex"
p "primitivo de F7" "@TEX corpus/docs/corpo_exercicios.tex"
p "fermat pelo grupo" "@TEX corpus/docs/corpo_exercicios.tex"
p "pequeno fermat pelo grupo" "@TEX corpus/docs/corpo_exercicios.tex"
p "inverso por euclides" "@TEX corpus/docs/corpo_exercicios.tex"
p "a orbita e o corpo" "@TEX corpus/docs/corpo_exercicios.tex"
p "euclides mdc bezout inverso corpo" "@TEX corpus/docs/corpo_exercicios.tex"

# álgebra moderna AL1–AL8
p "algebra moderna" "@TEX corpus/docs/algebra_moderna.tex"
p "o neutro e unico" "@TEX corpus/docs/algebra_moderna.tex"
p "identidade unica" "@TEX corpus/docs/algebra_moderna.tex"
p "inverso unico no grupo" "@TEX corpus/docs/algebra_moderna.tex"
p "cancelamento em grupo" "@TEX corpus/docs/algebra_moderna.tex"
p "todo subgrupo contem o neutro" "@TEX corpus/docs/algebra_moderna.tex"
p "intersecao de subgrupos" "@TEX corpus/docs/algebra_moderna.tex"
p "imagem de homomorfismo" "@TEX corpus/docs/algebra_moderna.tex"
p "nucleo e normal" "@TEX corpus/docs/algebra_moderna.tex"
p "injetivo sse nucleo trivial" "@TEX corpus/docs/algebra_moderna.tex"
p "lagrange classes laterais" "@TEX corpus/docs/algebra_moderna.tex"
p "teorema de lagrange" "@TEX corpus/docs/algebra_moderna.tex"
p "cayley permutacoes" "@TEX corpus/docs/algebra_moderna.tex"
p "todo grupo e permutacoes" "@TEX corpus/docs/algebra_moderna.tex"
p "primeiro isomorfismo" "@TEX corpus/docs/algebra_moderna.tex"
p "G ker f cong Im f" "@TEX corpus/docs/algebra_moderna.tex"
p "ideais sao nucleos" "@TEX corpus/docs/algebra_moderna.tex"
p "iso de aneis" "@TEX corpus/docs/algebra_moderna.tex"
p "ideais de Z" "@TEX corpus/docs/algebra_moderna.tex"
p "todo ideal de Z e nZ" "@TEX corpus/docs/algebra_moderna.tex"
p "corpo e dominio" "@TEX corpus/docs/algebra_moderna.tex"
p "operacao a mais b mais 1" "@TEX corpus/docs/algebra_moderna.tex"
p "nao associativa" "@TEX corpus/docs/algebra_moderna.tex"
p "a menos b nao e associativa" "@TEX corpus/docs/algebra_moderna.tex"
p "todo grupo comuta" "@TEX corpus/docs/algebra_moderna.tex"
p "todo grupo e comutativo" "@TEX corpus/docs/algebra_moderna.tex"
p "recusa abeliano" "@TEX corpus/docs/algebra_moderna.tex"
p "exponencial soma produto" "@TEX corpus/docs/algebra_moderna.tex"
p "soma vira produto" "@TEX corpus/docs/algebra_moderna.tex"
p "menos vezes" "@TEX corpus/docs/algebra_moderna.tex"
p "oposto atravessa o produto" "@TEX corpus/docs/algebra_moderna.tex"

# cálculo I CL1–CL8
p "calculo I" "@TEX corpus/docs/calculo_exercicios.tex"
p "unicidade do limite" "@TEX corpus/docs/calculo_exercicios.tex"
p "o limite e unico" "@TEX corpus/docs/calculo_exercicios.tex"
p "limite da soma" "@TEX corpus/docs/calculo_exercicios.tex"
p "sanduiche" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema do sanduiche" "@TEX corpus/docs/calculo_exercicios.tex"
p "polinomio continuo" "@TEX corpus/docs/calculo_exercicios.tex"
p "valor intermediario" "@TEX corpus/docs/calculo_exercicios.tex"
p "bissecao e o corte" "@TEX corpus/docs/calculo_exercicios.tex"
p "derivada por quociente" "@TEX corpus/docs/calculo_exercicios.tex"
p "derivada e avaliacao" "@TEX corpus/docs/calculo_exercicios.tex"
p "regra do produto" "@TEX corpus/docs/calculo_exercicios.tex"
p "regra da cadeia" "@TEX corpus/docs/calculo_exercicios.tex"
p "fermat extremo interior" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema de fermat extremos" "@TEX corpus/docs/calculo_exercicios.tex"
p "rolle" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema de rolle" "@TEX corpus/docs/calculo_exercicios.tex"
p "valor medio" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema do valor medio" "@TEX corpus/docs/calculo_exercicios.tex"
p "monotonia" "@TEX corpus/docs/calculo_exercicios.tex"
p "extremos de x3 menos 3x" "@TEX corpus/docs/calculo_exercicios.tex"
p "soma de riemann" "@TEX corpus/docs/calculo_exercicios.tex"
p "telescopagem exacta" "@TEX corpus/docs/calculo_exercicios.tex"
p "propriedades da integral" "@TEX corpus/docs/calculo_exercicios.tex"
p "fundamental i" "@TEX corpus/docs/calculo_exercicios.tex"
p "teorema fundamental primeira forma" "@TEX corpus/docs/calculo_exercicios.tex#fundamental i"
p "teorema fundamental segunda forma" "@TEX corpus/docs/calculo_exercicios.tex#fundamental ii"
p "a volta do tfc" "@TEX corpus/docs/calculo_exercicios.tex#fundamental ii"
p "substituicao e a cadeia invertida" "@TEX corpus/docs/calculo_exercicios.tex#substituicao"
p "integracao por partes" "@TEX corpus/docs/calculo_exercicios.tex#integracao por partes"
p "partes e o produto invertido" "@TEX corpus/docs/calculo_exercicios.tex#integracao por partes"
p "analise completa de x3 menos 3x" "@TEX corpus/docs/calculo_exercicios.tex#analise completa"
p "traducao no corpo universal" "@TEX corpus/docs/calculo_exercicios.tex#traducao"
p "cada teorema no universal" "@TEX corpus/docs/calculo_exercicios.tex#traducao"
# análise real AR1–AR8
p "analise real" "@TEX corpus/docs/analise_exercicios.tex"
p "existencia do supremo" "@TEX corpus/docs/analise_exercicios.tex#supremo"
p "sup e inf separados" "@TEX corpus/docs/analise_exercicios.tex#supremo"
p "propriedade arquimediana" "@TEX corpus/docs/analise_exercicios.tex#arquimediana"
p "n construtivo para epsilon" "@TEX corpus/docs/analise_exercicios.tex#arquimediana"
p "ponto medio entre racionais" "@TEX corpus/docs/analise_exercicios.tex#densidade"
p "densidade de Q" "@TEX corpus/docs/analise_exercicios.tex#densidade"
p "irracionais densos sem avaliar" "@TEX corpus/docs/analise_exercicios.tex#irracionais densos"
p "corte de dedekind de raiz de 2" "@TEX corpus/docs/analise_exercicios.tex#dedekind"
p "cauchy sem usar o limite" "@TEX corpus/docs/analise_exercicios.tex#cauchy em Q"
p "completude duas direccoes" "@TEX corpus/docs/analise_exercicios.tex#completude"
p "cauchy equivale a supremo" "@TEX corpus/docs/analise_exercicios.tex#completude"
p "bolzano weierstrass procurada" "@TEX corpus/docs/analise_exercicios.tex#bolzano"
p "subsucessao por bissecao" "@TEX corpus/docs/analise_exercicios.tex#bolzano"
# análise real AR9–AR16
p "n construido de epsilon" "@TEX corpus/docs/analise_exercicios.tex#epsilon N"
p "limite com N explicito" "@TEX corpus/docs/analise_exercicios.tex#epsilon N"
p "dois limites provam divergencia" "@TEX corpus/docs/analise_exercicios.tex#duas subsucessoes"
p "limsup igual liminf" "@TEX corpus/docs/analise_exercicios.tex#limsup"
p "tres formas da continuidade" "@TEX corpus/docs/analise_exercicios.tex#tres continuidades"
p "continua e nao uniformemente" "@TEX corpus/docs/analise_exercicios.tex#uniforme"
p "um sobre x nao uniforme" "@TEX corpus/docs/analise_exercicios.tex#uniforme"
p "limite dentro do compacto" "@TEX corpus/docs/analise_exercicios.tex#compacto"
p "heine borel duas direccoes" "@TEX corpus/docs/analise_exercicios.tex#heine borel"
p "fechado limitado e compacto" "@TEX corpus/docs/analise_exercicios.tex#heine borel"
p "weierstrass atinge extremos" "@TEX corpus/docs/analise_exercicios.tex#weierstrass"
p "continua em compacto atinge" "@TEX corpus/docs/analise_exercicios.tex#weierstrass"
# análise real AR17–AR25
p "limite contra quociente" "@TEX corpus/docs/analise_exercicios.tex#derivada limite e quociente"
p "derivada limite e quociente" "@TEX corpus/docs/analise_exercicios.tex#derivada limite e quociente"
p "valor medio na analise" "@TEX corpus/docs/analise_exercicios.tex#valor medio na analise"
p "c pode ser irracional" "@TEX corpus/docs/analise_exercicios.tex#valor medio na analise"
p "rolle e o gume" "@TEX corpus/docs/analise_exercicios.tex#rolle e o gume"
p "gume de rolle" "@TEX corpus/docs/analise_exercicios.tex#rolle e o gume"
p "resto de taylor medido" "@TEX corpus/docs/analise_exercicios.tex#taylor"
p "criterios estruturais de series" "@TEX corpus/docs/analise_exercicios.tex#series"
p "xn pontual nao uniforme" "@TEX corpus/docs/analise_exercicios.tex#convergencia uniforme"
p "u menos l exacto" "@TEX corpus/docs/analise_exercicios.tex#riemann"
p "troca lim int sob que hipotese" "@TEX corpus/docs/analise_exercicios.tex#troca de limite"
p "cinco vias da completude" "@TEX corpus/docs/analise_exercicios.tex#cinco vias"
p "nenhuma arbitra as outras" "@TEX corpus/docs/analise_exercicios.tex#cinco vias"
# cálculo II C2-1–C2-8
p "calculo II" "@TEX corpus/docs/calculo2_exercicios.tex"
p "partes sai do produto" "@TEX corpus/docs/calculo2_exercicios.tex#partes"
p "integracao por partes no produto" "@TEX corpus/docs/calculo2_exercicios.tex#partes"
p "integral impropria p maior que 1" "@TEX corpus/docs/calculo2_exercicios.tex#impropria"
p "n sobre n mais 1 com N" "@TEX corpus/docs/calculo2_exercicios.tex#sequencia"
p "limitada monotona converge" "@TEX corpus/docs/calculo2_exercicios.tex#bolzano monotona"
p "serie e objecto formal" "@TEX corpus/docs/calculo2_exercicios.tex#serie"
p "termo geral necessario nao suficiente" "@TEX corpus/docs/calculo2_exercicios.tex#termo geral"
p "serie p por telescopagem" "@TEX corpus/docs/calculo2_exercicios.tex#serie p"
p "geometrica formal sem convergencia" "@TEX corpus/docs/calculo2_exercicios.tex#geometrica"
# cálculo II C2-9–C2-16
p "raio e os extremos a parte" "@TEX corpus/docs/calculo2_exercicios.tex#raio"
p "taylor pelos coeficientes" "@TEX corpus/docs/calculo2_exercicios.tex#taylor momentos"
p "coeficientes sao momentos" "@TEX corpus/docs/calculo2_exercicios.tex#taylor momentos"
p "exp seno cosseno nos coeficientes" "@TEX corpus/docs/calculo2_exercicios.tex#exp seno cosseno"
p "parciais formais e exactas" "@TEX corpus/docs/calculo2_exercicios.tex#parciais"
p "gradiente e o dual" "@TEX corpus/docs/calculo2_exercicios.tex#gradiente"
p "schwarz verificado nos coeficientes" "@TEX corpus/docs/calculo2_exercicios.tex#schwarz"
p "derivada e operador linear" "@TEX corpus/docs/calculo2_exercicios.tex#derivada linear"
p "cadeia multiplica matrizes" "@TEX corpus/docs/calculo2_exercicios.tex#cadeia multi"
# cálculo II C2-17–C2-21
p "hessiana e a assinatura" "@TEX corpus/docs/calculo2_exercicios.tex#hessiana"
p "sela minimo maximo degenerada" "@TEX corpus/docs/calculo2_exercicios.tex#hessiana"
p "lagrange multiplicadores" "@TEX corpus/docs/calculo2_exercicios.tex#lagrange multiplicadores"
p "gume da regularidade do vinculo" "@TEX corpus/docs/calculo2_exercicios.tex#lagrange multiplicadores"
p "fubini duas ordens" "@TEX corpus/docs/calculo2_exercicios.tex#fubini"
p "jacobiano medida de volume" "@TEX corpus/docs/calculo2_exercicios.tex#jacobiano"
p "green interior contra borda" "@TEX corpus/docs/calculo2_exercicios.tex#green"
p "borda determina o interior" "@TEX corpus/docs/calculo2_exercicios.tex#green"
# cálculo III C3-1–C3-8
p "calculo III" "@TEX corpus/docs/calculo3_exercicios.tex"
p "limite por caminhos em Rn" "@TEX corpus/docs/calculo3_exercicios.tex#limite por caminhos"
p "dois caminhos matam o limite" "@TEX corpus/docs/calculo3_exercicios.tex#limite por caminhos"
p "bola aberta substitui intervalo" "@TEX corpus/docs/calculo3_exercicios.tex#bola"
p "direcional e maior crescimento" "@TEX corpus/docs/calculo3_exercicios.tex#direcional"
p "plano tangente exacto no resto" "@TEX corpus/docs/calculo3_exercicios.tex#plano tangente"
p "diferencial e o funcional" "@TEX corpus/docs/calculo3_exercicios.tex#diferencial"
p "jacobiana multiplica operadores" "@TEX corpus/docs/calculo3_exercicios.tex#jacobiana"
p "taylor multi exacto" "@TEX corpus/docs/calculo3_exercicios.tex#taylor multi"
p "ponto critico quatro estados" "@TEX corpus/docs/calculo3_exercicios.tex#ponto critico"
# cálculo III C3-9–C3-16
p "lagrange vinculo regular" "@TEX corpus/docs/calculo3_exercicios.tex#lagrange vinculo"
p "integral multipla e fubini" "@TEX corpus/docs/calculo3_exercicios.tex#integral multipla"
p "jacobiano e a medida" "@TEX corpus/docs/calculo3_exercicios.tex#jacobiano volume"
p "coordenadas e o factor" "@TEX corpus/docs/calculo3_exercicios.tex#coordenadas"
p "div atravessa rot roda" "@TEX corpus/docs/calculo3_exercicios.tex#campo"
p "conservativo e a fibra" "@TEX corpus/docs/calculo3_exercicios.tex#conservativo"
p "trabalho independente do caminho" "@TEX corpus/docs/calculo3_exercicios.tex#trabalho"
p "integral de linha e circulacao" "@TEX corpus/docs/calculo3_exercicios.tex#integral de linha"
# cálculo III C3-17–C3-21
p "fluxo pela superficie" "@TEX corpus/docs/calculo3_exercicios.tex#fluxo"
p "green no plano" "@TEX corpus/docs/calculo3_exercicios.tex#green no plano"
p "stokes rot face" "@TEX corpus/docs/calculo3_exercicios.tex#stokes rot face"
p "gauss fluxo caixa" "@TEX corpus/docs/calculo3_exercicios.tex#gauss fluxo caixa"
p "green stokes gauss mesma estrutura" "@TEX corpus/docs/calculo3_exercicios.tex#a mesma estrutura"
p "falta o d exterior" "@TEX corpus/docs/calculo3_exercicios.tex#a mesma estrutura"
# formas diferenciais DF1–DF8
p "formas diferenciais" "@TEX corpus/docs/formas_exercicios.tex"
p "tres lugares para toda forma" "@TEX corpus/docs/formas_exercicios.tex#forma"
p "derivada exterior uma vez" "@TEX corpus/docs/formas_exercicios.tex#derivada exterior"
p "d e o gradiente" "@TEX corpus/docs/formas_exercicios.tex#d e grad"
p "d e o rotacional" "@TEX corpus/docs/formas_exercicios.tex#d e rot"
p "d e a divergencia" "@TEX corpus/docs/formas_exercicios.tex#d e div"
p "d ao quadrado e zero" "@TEX corpus/docs/formas_exercicios.tex#d ao quadrado"
p "o complexo das formas" "@TEX corpus/docs/formas_exercicios.tex#o complexo"
p "cunha directo e cruzado" "@TEX corpus/docs/formas_exercicios.tex#cunha"
# formas diferenciais DF9–DF16
p "leibniz graduada e o sinal" "@TEX corpus/docs/formas_exercicios.tex#leibniz"
p "estrela involucao" "@TEX corpus/docs/formas_exercicios.tex#estrela"
p "contracao espelha d2" "@TEX corpus/docs/formas_exercicios.tex#contracao"
p "directo e cruzado na mesma lingua" "@TEX corpus/docs/formas_exercicios.tex#directo e cruzado"
p "stokes uma vez so" "@TEX corpus/docs/formas_exercicios.tex#stokes uma vez"
p "green e stokes grau 1" "@TEX corpus/docs/formas_exercicios.tex#green grau 1"
p "gauss e stokes grau 2" "@TEX corpus/docs/formas_exercicios.tex#gauss grau 2"
p "fechada e exacta poincare" "@TEX corpus/docs/formas_exercicios.tex#fechada e exacta"
# formas diferenciais DF17–DF21 (fecha catálogo)
p "potencial primitiva de formas" "@TEX corpus/docs/formas_exercicios.tex#potencial"
p "adjuncao borda e d" "@TEX corpus/docs/formas_exercicios.tex#adjuncao"
p "dimensao C3k e estrela" "@TEX corpus/docs/formas_exercicios.tex#dimensao"
p "o buraco onde fechada nao exacta" "@TEX corpus/docs/formas_exercicios.tex#o buraco"
p "a linguagem unica tudo junto" "@TEX corpus/docs/formas_exercicios.tex#a linguagem unica"
# topologia TP1–TP8
p "topologia" "@TEX corpus/docs/topologia_exercicios.tex"
p "axiomas uniao e intersecao" "@TEX corpus/docs/topologia_exercicios.tex#axiomas"
p "base gera topologia" "@TEX corpus/docs/topologia_exercicios.tex#base"
p "discreta vs indiscreta" "@TEX corpus/docs/topologia_exercicios.tex#discreta"
p "subespaco por traco" "@TEX corpus/docs/topologia_exercicios.tex#subespaco"
p "fecho por duas vias" "@TEX corpus/docs/topologia_exercicios.tex#fecho"
p "fronteira quatro diferentes" "@TEX corpus/docs/topologia_exercicios.tex#fronteira"
p "acumulacao e isolados" "@TEX corpus/docs/topologia_exercicios.tex#acumulacao"
p "hausdorff e sierpinski" "@TEX corpus/docs/topologia_exercicios.tex#hausdorff"
# topologia TP9–TP16
p "continuidade sem distancia" "@TEX corpus/docs/topologia_exercicios.tex#continuidade"
p "continuidade por fechados" "@TEX corpus/docs/topologia_exercicios.tex#por fechados"
p "homeomorfismo procura inversa" "@TEX corpus/docs/topologia_exercicios.tex#homeomorfismo"
p "sequencias metricas vs topologicas" "@TEX corpus/docs/topologia_exercicios.tex#sequencias"
p "compacto por cobertura aberta" "@TEX corpus/docs/topologia_exercicios.tex#compacto por cobertura"
p "heine borel duas direcoes" "@TEX corpus/docs/topologia_exercicios.tex#heine borel"
p "imagem continua de compacto" "@TEX corpus/docs/topologia_exercicios.tex#imagem de compacto"
p "compacto em hausdorff e gume" "@TEX corpus/docs/topologia_exercicios.tex#compacto em hausdorff"
# topologia TP17–TP20 (fecha catálogo)
p "conexo por separacao" "@TEX corpus/docs/topologia_exercicios.tex#conexo"
p "conexidade da reta e Q" "@TEX corpus/docs/topologia_exercicios.tex#conexidade da reta"
p "produto vs metrica induzida" "@TEX corpus/docs/topologia_exercicios.tex#produto"
p "remova a metrica gume" "@TEX corpus/docs/topologia_exercicios.tex#remova a metrica"
# espaços métricos MT1–MT8
p "espacos metricos" "@TEX corpus/docs/metrico_exercicios.tex"
p "metrica quatro axiomas" "@TEX corpus/docs/metrico_exercicios.tex#metrica"
p "bola aberta racional" "@TEX corpus/docs/metrico_exercicios.tex#bola aberta racional"
p "convergencia N de epsilon" "@TEX corpus/docs/metrico_exercicios.tex#convergencia"
p "cauchy sem limite em Q" "@TEX corpus/docs/metrico_exercicios.tex#cauchy sem limite"
p "dois espacos mesma sucessao" "@TEX corpus/docs/metrico_exercicios.tex#dois espacos"
p "incompleto Q testemunha" "@TEX corpus/docs/metrico_exercicios.tex#incompleto"
p "lipschitz q identificado" "@TEX corpus/docs/metrico_exercicios.tex#lipschitz"
p "ponto fixo por contracao" "@TEX corpus/docs/metrico_exercicios.tex#ponto fixo"
# espaços métricos MT9–MT16 (fecha catálogo)
p "banach existencia e unicidade" "@TEX corpus/docs/metrico_exercicios.tex#banach"
p "isometria vs contracao" "@TEX corpus/docs/metrico_exercicios.tex#isometria"
p "duas metricas equivalentes" "@TEX corpus/docs/metrico_exercicios.tex#duas metricas"
p "continuidade lipschitz derivada" "@TEX corpus/docs/metrico_exercicios.tex#continuidade lipschitz"
p "fecho metrico duas inclusoes" "@TEX corpus/docs/metrico_exercicios.tex#fecho metrico"
p "completamento relacao cauchy" "@TEX corpus/docs/metrico_exercicios.tex#completamento"
p "gume buscador Q e R" "@TEX corpus/docs/metrico_exercicios.tex#gume"
p "sintese do andar metrico" "@TEX corpus/docs/metrico_exercicios.tex#sintese do andar"
# homotopia HM1–HM14 (fecha catálogo)
p "homotopia" "@TEX corpus/docs/homotopia_exercicios.tex"
p "posto pi1 livre grafo" "@TEX corpus/docs/homotopia_exercicios.tex#posto"
p "contractil posto zero grafo" "@TEX corpus/docs/homotopia_exercicios.tex#contractil"
p "euler chi e posto grafo" "@TEX corpus/docs/homotopia_exercicios.tex#euler"
p "o buraco nenhum ponto ve" "@TEX corpus/docs/homotopia_exercicios.tex#o buraco nenhum ponto"
p "voltas inteiro aresta" "@TEX corpus/docs/homotopia_exercicios.tex#voltas"
p "pi1 do circulo e Z" "@TEX corpus/docs/homotopia_exercicios.tex#pi1 do circulo"
p "laco trivial w zero" "@TEX corpus/docs/homotopia_exercicios.tex#laco trivial"
p "o oito nao abeliano" "@TEX corpus/docs/homotopia_exercicios.tex#o oito"
p "comutador nao reduz" "@TEX corpus/docs/homotopia_exercicios.tex#comutador"
p "abelianizacao oito e toro" "@TEX corpus/docs/homotopia_exercicios.tex#abelianizacao"
p "invariante so distingue" "@TEX corpus/docs/homotopia_exercicios.tex#invariante"
p "local e global colagem" "@TEX corpus/docs/homotopia_exercicios.tex#local e global"
p "recobrimento levantamento" "@TEX corpus/docs/homotopia_exercicios.tex#recobrimento"
p "a torre do andar metrico a pi1" "@TEX corpus/docs/homotopia_exercicios.tex#a torre do andar"
# ponte PN1–PN10 (fecha catálogo)
p "ponte cohomologia" "@TEX corpus/docs/ponte_exercicios.tex"
p "local e global ponte lei" "@TEX corpus/docs/ponte_exercicios.tex#local e global ponte"
p "a colagem invariante global" "@TEX corpus/docs/ponte_exercicios.tex#a colagem"
p "o complexo no grafo H1" "@TEX corpus/docs/ponte_exercicios.tex#o complexo no grafo"
p "dois caminhos gauss e contagem" "@TEX corpus/docs/ponte_exercicios.tex#dois caminhos"
p "a testemunha omega no ciclo" "@TEX corpus/docs/ponte_exercicios.tex#a testemunha"
p "ciclo menos borda peano" "@TEX corpus/docs/ponte_exercicios.tex#ciclo menos borda"
p "fechada menos exacta estelar" "@TEX corpus/docs/ponte_exercicios.tex#fechada menos exacta"
p "a adjuncao incidencia" "@TEX corpus/docs/ponte_exercicios.tex#a adjuncao incidencia"
p "nao linear pi1 e H1" "@TEX corpus/docs/ponte_exercicios.tex#nao linear"
p "a representacao do buraco" "@TEX corpus/docs/ponte_exercicios.tex#a representacao"
# hierarquia HI1–HI9 (fecha catálogo)
p "hierarquia tres camadas" "@TEX corpus/docs/hierarquia_exercicios.tex"
p "hierarquia universal peano estelar" "@TEX corpus/docs/hierarquia_exercicios.tex#hierarquia"
p "a lei stokes estrutural" "@TEX corpus/docs/hierarquia_exercicios.tex#a lei"
p "sem teto dimensional linguagem" "@TEX corpus/docs/hierarquia_exercicios.tex#sem teto dimensional"
p "separacao por idempotencia" "@TEX corpus/docs/hierarquia_exercicios.tex#separacao"
p "conservacao por simetria" "@TEX corpus/docs/hierarquia_exercicios.tex#conservacao"
p "face de peano diferencial b zero" "@TEX corpus/docs/hierarquia_exercicios.tex#face de peano"
p "face do estelar graduacao" "@TEX corpus/docs/hierarquia_exercicios.tex#face do estelar"
p "instancias green stokes gauss" "@TEX corpus/docs/hierarquia_exercicios.tex#instancias"
p "o que nao afirmo fronteira" "@TEX corpus/docs/hierarquia_exercicios.tex#o que nao afirmo"
# universal UN1–UN23 (fecha catálogo)
p "universal corpo" "@TEX corpus/docs/universal_exercicios.tex"
p "escada estrita filtracao" "@TEX corpus/docs/universal_exercicios.tex#escada estrita"
p "teto do observador vandermonde" "@TEX corpus/docs/universal_exercicios.tex#teto do observador"
p "duas fusoes energia" "@TEX corpus/docs/universal_exercicios.tex#duas fusoes"
p "divisao e fibra preimagem" "@TEX corpus/docs/universal_exercicios.tex#divisao e fibra"
p "absorcao endereco residuo" "@TEX corpus/docs/universal_exercicios.tex#absorcao"
p "parseval ntt multidimensional" "@TEX corpus/docs/universal_exercicios.tex#parseval"
p "borda de dirac caracteristica" "@TEX corpus/docs/universal_exercicios.tex#borda de dirac"
p "a obstrucao raiz do passo" "@TEX corpus/docs/universal_exercicios.tex#a obstrucao"
p "dirac nas transicoes diagonal" "@TEX corpus/docs/universal_exercicios.tex#dirac nas transicoes"
p "dobra temporal polinomio" "@TEX corpus/docs/universal_exercicios.tex#dobra temporal"
p "recobrimento discriminante dobra" "@TEX corpus/docs/universal_exercicios.tex#recobrimento discriminante"
p "contornos cinquenta e dois" "@TEX corpus/docs/universal_exercicios.tex#contornos"
p "cartas da torcao complexos" "@TEX corpus/docs/universal_exercicios.tex#cartas da torcao"
p "zeta dinamica censo orbitas" "@TEX corpus/docs/universal_exercicios.tex#zeta dinamica"
p "residuos relogio finito" "@TEX corpus/docs/universal_exercicios.tex#residuos"
p "produto dual quatro niveis" "@TEX corpus/docs/universal_exercicios.tex#produto dual"
p "par morfologico adjuncao" "@TEX corpus/docs/universal_exercicios.tex#par morfologico"
p "torcao duas realizacoes" "@TEX corpus/docs/universal_exercicios.tex#torcao"
p "estrutura corpo por nivel" "@TEX corpus/docs/universal_exercicios.tex#estrutura"
p "o real e um caminho arvore" "@TEX corpus/docs/universal_exercicios.tex#o real e um caminho"
p "geometria de klein erlangen" "@TEX corpus/docs/universal_exercicios.tex#geometria de klein"
p "memoria projector espectral" "@TEX corpus/docs/universal_exercicios.tex#memoria"
p "dicionario traduz consagrado" "@TEX corpus/docs/universal_exercicios.tex#dicionario"
# torre TR1–TR16 (fecha catálogo)
p "torre cayley dickson" "@TEX corpus/docs/torre_exercicios.tex"
p "complexos norma multiplicativa" "@TEX corpus/docs/torre_exercicios.tex#complexos"
p "quaternioes ij anticomuta" "@TEX corpus/docs/torre_exercicios.tex#quaternioes"
p "inverso pela norma fibra" "@TEX corpus/docs/torre_exercicios.tex#inverso"
p "produto directo cruzado torre" "@TEX corpus/docs/torre_exercicios.tex#produto directo cruzado"
p "octonioes nao associativos" "@TEX corpus/docs/torre_exercicios.tex#octonioes"
p "alternatividade em O" "@TEX corpus/docs/torre_exercicios.tex#alternatividade"
p "comutador na torre aparece" "@TEX corpus/docs/torre_exercicios.tex#comutador na torre"
p "associador H zero O testemunha" "@TEX corpus/docs/torre_exercicios.tex#associador"
p "cayley dickson escada perdas" "@TEX corpus/docs/torre_exercicios.tex#cayley dickson"
p "a fronteira norma e divisao" "@TEX corpus/docs/torre_exercicios.tex#a fronteira"
p "a torre pelo dual estrela" "@TEX corpus/docs/torre_exercicios.tex#a torre pelo dual"
p "octoniao dual H vezes H" "@TEX corpus/docs/torre_exercicios.tex#octoniao dual"
p "onde a norma morre acima de 8" "@TEX corpus/docs/torre_exercicios.tex#onde a norma morre"
p "gentil soma reversivel" "@TEX corpus/docs/torre_exercicios.tex#gentil"
p "lebesgue corte imagem dominio" "@TEX corpus/docs/torre_exercicios.tex#lebesgue"
p "teorema central hurwitz gentil" "@TEX corpus/docs/torre_exercicios.tex#teorema central"
# álgebra exterior EX1–EX15
p "algebra exterior exercicios" "@TEX corpus/docs/exterior_exercicios.tex"
p "produto tensorial dim" "@TEX corpus/docs/exterior_exercicios.tex#produto tensorial"
p "propriedade universal do tensor" "@TEX corpus/docs/exterior_exercicios.tex#propriedade universal"
p "formas multilineares e lambda" "@TEX corpus/docs/exterior_exercicios.tex#formas multilineares"
p "algebra exterior quociente" "@TEX corpus/docs/exterior_exercicios.tex#algebra exterior"
p "wedge menores e quadrado nulo" "@TEX corpus/docs/exterior_exercicios.tex#wedge"
p "determinante volume orientado" "@TEX corpus/docs/exterior_exercicios.tex#determinante"
p "orientacao sinal do det" "@TEX corpus/docs/exterior_exercicios.tex#orientacao"
p "hodge estrela involucao" "@TEX corpus/docs/exterior_exercicios.tex#hodge"
p "identificacao forma dual" "@TEX corpus/docs/exterior_exercicios.tex#identificacao"
p "contracao antiderivacao" "@TEX corpus/docs/exterior_exercicios.tex#contracao"
p "dualidade exterior lambda" "@TEX corpus/docs/exterior_exercicios.tex#dualidade exterior"
p "produto misto volume" "@TEX corpus/docs/exterior_exercicios.tex#produto misto"
p "pfaffiano raiz polinomial" "@TEX corpus/docs/exterior_exercicios.tex#pfaffiano"
p "cruzado so em dimensao 3" "@TEX corpus/docs/exterior_exercicios.tex#cruzado"
p "fecho do dual directo cruzado" "@TEX corpus/docs/exterior_exercicios.tex#fecho do dual"
# formas / tensores TS1–TS16
p "formas e tensores exercicios" "@TEX corpus/docs/tensor_exercicios.tex"
p "matriz de gram coordenadas" "@TEX corpus/docs/tensor_exercicios.tex#gram"
p "congruencia mudanca de base" "@TEX corpus/docs/tensor_exercicios.tex#congruencia"
p "polarizacao da forma quadratica" "@TEX corpus/docs/tensor_exercicios.tex#polarizacao"
p "caracteristica 2 contra exemplo" "@TEX corpus/docs/tensor_exercicios.tex#caracteristica 2"
p "assinatura testemunhas forma" "@TEX corpus/docs/tensor_exercicios.tex#assinatura"
p "sylvester assinatura invariante" "@TEX corpus/docs/tensor_exercicios.tex#sylvester"
p "semidefinida e indefinida" "@TEX corpus/docs/tensor_exercicios.tex#semidefinida"
p "polinomio minimo menor" "@TEX corpus/docs/tensor_exercicios.tex#polinomio minimo"
p "similaridade preserva espectro" "@TEX corpus/docs/tensor_exercicios.tex#similaridade"
p "mesmo espectro nao semelhante" "@TEX corpus/docs/tensor_exercicios.tex#mesmo espectro"
p "autoespaco blocos jordan" "@TEX corpus/docs/tensor_exercicios.tex#autoespaco"
p "matrizes normais espectral" "@TEX corpus/docs/tensor_exercicios.tex#normais"
p "eixos da forma espectral" "@TEX corpus/docs/tensor_exercicios.tex#eixos da forma"
p "tensor bilinear linear" "@TEX corpus/docs/tensor_exercicios.tex#tensor"
p "exterior volume determinante" "@TEX corpus/docs/tensor_exercicios.tex#exterior"
p "nucleo do dual estrutural" "@TEX corpus/docs/tensor_exercicios.tex#nucleo do dual estrutural"
# formas bilineares / espectro FQ1–FQ16
p "formas bilineares espectro" "@TEX corpus/docs/forma_exercicios.tex"
p "bilinear em cada argumento" "@TEX corpus/docs/forma_exercicios.tex#bilinear"
p "simetrica forma matriz" "@TEX corpus/docs/forma_exercicios.tex#simetrica"
p "quadratica gume zero" "@TEX corpus/docs/forma_exercicios.tex#quadratica"
p "produto interno tres condicoes" "@TEX corpus/docs/forma_exercicios.tex#produto interno"
p "cauchy schwarz ao quadrado" "@TEX corpus/docs/forma_exercicios.tex#cauchy schwarz"
p "desigualdade triangular norma" "@TEX corpus/docs/forma_exercicios.tex#triangular"
p "ortogonalidade complemento" "@TEX corpus/docs/forma_exercicios.tex#ortogonalidade"
p "projecao ortogonal exacta" "@TEX corpus/docs/forma_exercicios.tex#projecao"
p "gram schmidt base ortogonal" "@TEX corpus/docs/forma_exercicios.tex#gram schmidt"
p "adjunto transposta" "@TEX corpus/docs/forma_exercicios.tex#adjunto"
p "teorema espectral simetrica" "@TEX corpus/docs/forma_exercicios.tex#espectral"
p "valores singulares exactos" "@TEX corpus/docs/forma_exercicios.tex#valores singulares"
p "svd rotacao escala" "@TEX corpus/docs/forma_exercicios.tex#svd"
p "cayley hamilton reduz" "@TEX corpus/docs/forma_exercicios.tex#cayley hamilton"
p "jordan nao diagonalizavel" "@TEX corpus/docs/forma_exercicios.tex#jordan"
p "a casa ja tinha formas" "@TEX corpus/docs/forma_exercicios.tex#a casa ja tinha"
# álgebra linear LI1–LI16
p "algebra linear exercicios" "@TEX corpus/docs/linear_exercicios.tex"
p "espaco vetorial oito leis" "@TEX corpus/docs/linear_exercicios.tex#espaco vetorial"
p "vetor zero unico linear" "@TEX corpus/docs/linear_exercicios.tex#vetor zero unico"
p "subespaco teste minimo" "@TEX corpus/docs/linear_exercicios.tex#subespaco"
p "span menor subespaco" "@TEX corpus/docs/linear_exercicios.tex#span"
p "independencia linear combinacao" "@TEX corpus/docs/linear_exercicios.tex#independencia"
p "base e coordenada unicas" "@TEX corpus/docs/linear_exercicios.tex#base e coordenada"
p "matrizes produto convolucao" "@TEX corpus/docs/linear_exercicios.tex#matrizes"
p "nao comuta ab ba" "@TEX corpus/docs/linear_exercicios.tex#nao comuta"
p "transformacao linear def" "@TEX corpus/docs/linear_exercicios.tex#transformacao"
p "nucleo e imagem fibra" "@TEX corpus/docs/linear_exercicios.tex#nucleo e imagem"
p "posto nulidade dimensao" "@TEX corpus/docs/linear_exercicios.tex#posto nulidade"
p "isomorfismo bijetiva inversa" "@TEX corpus/docs/linear_exercicios.tex#isomorfismo"
p "determinante invertivel produto" "@TEX corpus/docs/linear_exercicios.tex#determinante"
p "sistemas ax b fibra" "@TEX corpus/docs/linear_exercicios.tex#sistemas"
p "autovalores caracteristico" "@TEX corpus/docs/linear_exercicios.tex#autovalores"
p "diagonalizacao potencias" "@TEX corpus/docs/linear_exercicios.tex#diagonalizacao"
# espaço dual DU1–DU14
p "espaco dual exercicios" "@TEX corpus/docs/dual_exercicios.tex"
p "dual medicoes lineares" "@TEX corpus/docs/dual_exercicios.tex#dual"
p "dual e espaco ponto a ponto" "@TEX corpus/docs/dual_exercicios.tex#dual e espaco"
p "funcional no dual" "@TEX corpus/docs/dual_exercicios.tex#funcional"
p "base dual delta" "@TEX corpus/docs/dual_exercicios.tex#base dual"
p "coordenada e medida dual" "@TEX corpus/docs/dual_exercicios.tex#coordenada e medida"
p "dimensao do dual igual" "@TEX corpus/docs/dual_exercicios.tex#dimensao do dual"
p "base dual de B" "@TEX corpus/docs/dual_exercicios.tex#base dual de B"
p "bidual iota" "@TEX corpus/docs/dual_exercicios.tex#bidual"
p "iota injetiva canonico" "@TEX corpus/docs/dual_exercicios.tex#iota injetiva"
p "nao canonico V Vstar" "@TEX corpus/docs/dual_exercicios.tex#nao canonico"
p "aniquilador W grau" "@TEX corpus/docs/dual_exercicios.tex#aniquilador"
p "dimensao anulador soma" "@TEX corpus/docs/dual_exercicios.tex#dimensao anulador"
p "dual da transformacao adjunto" "@TEX corpus/docs/dual_exercicios.tex#dual da transformacao"
p "nucleo do dual chefao" "@TEX corpus/docs/dual_exercicios.tex#nucleo do dual"
# curvas elípticas EL1–EL12
p "curvas elipticas exercicios" "@TEX corpus/docs/eliptica_exercicios.tex"
p "ponto no infinito neutro" "@TEX corpus/docs/eliptica_exercicios.tex#infinito"
p "negacao reflexao curva" "@TEX corpus/docs/eliptica_exercicios.tex#negacao"
p "soma secante eliptica" "@TEX corpus/docs/eliptica_exercicios.tex#soma"
p "porque viete cubica" "@TEX corpus/docs/eliptica_exercicios.tex#porque"
p "dobro tangente gume" "@TEX corpus/docs/eliptica_exercicios.tex#dobro"
p "exemplo quatro P infinito" "@TEX corpus/docs/eliptica_exercicios.tex#exemplo"
p "grupo associatividade eliptica" "@TEX corpus/docs/eliptica_exercicios.tex#grupo"
p "comutatividade P Q" "@TEX corpus/docs/eliptica_exercicios.tex#comutatividade"
p "corpo finito inversao modular" "@TEX corpus/docs/eliptica_exercicios.tex#corpo finito"
p "contar pontos F17" "@TEX corpus/docs/eliptica_exercicios.tex#contar"
p "lagrange ordem divide" "@TEX corpus/docs/eliptica_exercicios.tex#lagrange"
p "double and add 19P" "@TEX corpus/docs/eliptica_exercicios.tex#double and add"
# teoria dos números TN1–TN17
p "teoria numeros exercicios" "@TEX corpus/docs/numeros_exercicios.tex"
p "divisibilidade transitiva" "@TEX corpus/docs/numeros_exercicios.tex#divisibilidade"
p "mdc euclides identidade" "@TEX corpus/docs/numeros_exercicios.tex#mdc euclides"
p "bezout menor positivo" "@TEX corpus/docs/numeros_exercicios.tex#bezout menor"
p "euclides estendido coeficientes" "@TEX corpus/docs/numeros_exercicios.tex#euclides estendido"
p "lema de euclides primo" "@TEX corpus/docs/numeros_exercicios.tex#lema de euclides"
p "fatoracao unica aritmetica" "@TEX corpus/docs/numeros_exercicios.tex#fatoracao unica"
p "infinitos primos construcao" "@TEX corpus/docs/numeros_exercicios.tex#infinitos primos"
p "congruencias sem calcular" "@TEX corpus/docs/numeros_exercicios.tex#congruencias"
p "inverso modular 17 mod 43" "@TEX corpus/docs/numeros_exercicios.tex#inverso modular"
p "fermat pequeno potencia" "@TEX corpus/docs/numeros_exercicios.tex#fermat"
p "totiente phi 60" "@TEX corpus/docs/numeros_exercicios.tex#totiente"
p "euler totiente congruencia" "@TEX corpus/docs/numeros_exercicios.tex#euler"
p "chines restos sistema" "@TEX corpus/docs/numeros_exercicios.tex#chines"
p "diofantina todas solucoes" "@TEX corpus/docs/numeros_exercicios.tex#diofantina"
p "fracao continua euclides" "@TEX corpus/docs/numeros_exercicios.tex#fracao continua"
p "mobius soma divisores" "@TEX corpus/docs/numeros_exercicios.tex#mobius"
p "a orbita unica euclides" "@TEX corpus/docs/numeros_exercicios.tex#a orbita unica"
# provas reais EX20
p "provas reais exercicios" "@TEX corpus/docs/reais_exercicios.tex"
p "modulo positivo ordem" "@TEX corpus/docs/reais_exercicios.tex#modulo positivo"
p "modulo produto sinais" "@TEX corpus/docs/reais_exercicios.tex#modulo produto"
p "triangular modulo soma" "@TEX corpus/docs/reais_exercicios.tex#triangular"
p "quadrado positivo sinais" "@TEX corpus/docs/reais_exercicios.tex#quadrado positivo"
p "modulo epsilon intervalo" "@TEX corpus/docs/reais_exercicios.tex#modulo epsilon"
p "racional entre densos" "@TEX corpus/docs/reais_exercicios.tex#racional entre"
p "irracional entre densos" "@TEX corpus/docs/reais_exercicios.tex#irracional entre"
p "monotona limitada converge" "@TEX corpus/docs/reais_exercicios.tex#monotona"
p "convergente e cauchy" "@TEX corpus/docs/reais_exercicios.tex#convergente cauchy"
p "limite unico quando existe" "@TEX corpus/docs/reais_exercicios.tex#limite unico"
p "completude axioma supremo" "@TEX corpus/docs/reais_exercicios.tex#completude"
p "corte de dedekind raiz2" "@TEX corpus/docs/reais_exercicios.tex#corte de dedekind"
p "raiz dois nao racional" "@TEX corpus/docs/reais_exercicios.tex#raiz dois"
p "intervalos encaixados ponto" "@TEX corpus/docs/reais_exercicios.tex#encaixados"
p "bolzano weierstrass prova" "@TEX corpus/docs/reais_exercicios.tex#bolzano"
p "existencia raiz positiva" "@TEX corpus/docs/reais_exercicios.tex#existencia raiz"
p "valor intermediario teorema" "@TEX corpus/docs/reais_exercicios.tex#valor intermediario"
p "racionais densos em R" "@TEX corpus/docs/reais_exercicios.tex#racionais densos"
p "irracionais densos em R" "@TEX corpus/docs/reais_exercicios.tex#irracionais densos"
p "cauchy converge em R" "@TEX corpus/docs/reais_exercicios.tex#cauchy converge"
